# Generated by Django 4.0.4 on 2022-06-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name_plural': 'Contact Page'},
        ),
        migrations.AlterModelOptions(
            name='help_choices',
            options={'verbose_name_plural': 'Help Choices'},
        ),
        migrations.AlterModelOptions(
            name='maillist',
            options={'verbose_name_plural': 'Mail List'},
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='any_other_area_of_help',
            new_name='any_other_area_you_would_like_to_help',
        ),
    ]
