# Generated by Django 4.0.4 on 2022-06-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_contactpage_options_alter_help_choices_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='any_other_details',
            new_name='mentor_any_other_details',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='area_of_interest',
            new_name='mentor_area_of_interest',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='company',
            new_name='mentor_company',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='country',
            new_name='mentor_country',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='email',
            new_name='mentor_email',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='firstname',
            new_name='mentor_firstname',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='lastname',
            new_name='mentor_lastname',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='any_other_area_you_would_like_to_help',
            new_name='volunteer_any_other_area_you_would_like_to_help',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='country',
            new_name='volunteer_country',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='email',
            new_name='volunteer_email',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='firstname',
            new_name='volunteer_firstname',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='lastname',
            new_name='volunteer_lastname',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='what_can_you_help_with',
            new_name='volunteer_what_can_you_help_with',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='why_would_you_like_to_help',
            new_name='volunteer_why_would_you_like_to_help',
        ),
    ]
