# Generated by Django 4.0.4 on 2022-06-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_any_other_details_mentor_mentor_any_other_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='mentor_any_other_details',
            new_name='any_other_details',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mentor_area_of_interest',
            new_name='area_of_interest',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mentor_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mentor_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mentor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mentor_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mentor_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_any_other_area_you_would_like_to_help',
            new_name='any_other_area_you_would_like_to_help',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_what_can_you_help_with',
            new_name='what_can_you_help_with',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_why_would_you_like_to_help',
            new_name='why_would_you_like_to_help',
        ),
    ]
